### ISSUE TITLE
OSError on rp2040 w/ CircuitPython 7.3.3

### ISSUE THREAD

**Issue by adamwmeek** [arturo182/arturo182_CircuitPython_BBQ10Keyboard#2]
When trying to use this library on an rp2040 (specifically the Adafruit Feather rp2040) I get this traceback:

```
Traceback (most recent call last):
  File "code.py", line 70, in <module>
  File "bbq10keyboard.py", line 116, in key_count
  File "bbq10keyboard.py", line 109, in status
OSError: [Errno 19] No such device
```

Snippit of my code:

```
command = ''

def handle_keyboard(pressed):

    if pressed == '\b':
        command = command[:l-1]
    elif pressed == 10: #enter
        command = ''
    else:
        command = command + pressed

    time.sleep(0.03)

while True:
    key_count = kbd.key_count
    if key_count > 0:
        key = kbd.key
        handle_keyboard(key)
```

I have tried with CircuitPython 7.3.3 and 8.0.0-beta.0 and I get the same result each time. 

(FYI: I suspect this might be an issue with CircuitPython, as it seems related to [this](https://github.com/adafruit/Adafruit_CircuitPython_AM2320/issues/27). Just wanted to document this so you know! <3)

**Comment by arturo182** [comment]
Thanks for the info, a bit weird cause I tested the library on the RP2040 and there were no problems. I think it was with 7.1, so maybe something got broken in CPY after that. Maybe you can revert to an older version for now?

**Comment by adamwmeek** [comment]
Nevermind! I was either initializing I2C or the keyboard incorrectly. All is working with CPY 7.1, 7.2, 7.3.3, and 8.0.0-beta.0

**Comment by arturo182** [comment]
Glad to hear! :)
